In [ ]:
import pandas as pd
import random

:

In [99]:
actors = pd.read_html('actors.html')
casts  = pd.read_html('casts.html')

In [100]:
actorsTable = pd.DataFrame(columns = ['stage', 'dow', 'birth', 'giv', 'gen', 'dob', 'dod', 'type', 'orig',
                         'pict', 'notes'])
for table in actors:
  data = pd.DataFrame(data = table[['stage', 'dow', 'birth', 'giv', 'gen', 'dob', 'dod', 'type', 'orig',
                         'pict', 'notes']])
  actorsTable = actorsTable.append(data, ignore_index=True)

In [150]:
castsTable = pd.DataFrame(columns = ['movie', 'actor', 'type', 'role'])
for table in casts:
  first_column = table.iloc[:, 1]
  print(first_column.name)
  print(table.info())
  if((first_column.name != 'title') and (first_column.name != 1) and (first_column.name != 'actor')):
    try:
      data = pd.DataFrame(data = table[[first_column.name, 'actor', 'type', 'role']])
      data = data.rename(columns = {first_column.name: 'movie'})
    except:
      try:
        data = pd.DataFrame(data = table[[first_column.name, 'actot', 'type', 'role']])
        data = data.rename(columns = {first_column.name: 'movie', 'actot':'actor'})
      except:
        print('error')
        break;

    castsTable = castsTable.append(data, ignore_index=True)
    castsTable.reset_index()

Streaming output truncated to the last 5000 lines.
 8   |             0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 488.0+ bytes
None
D:A.Bragaglia
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   AB             1 non-null      object
 1   D:A.Bragaglia  1 non-null      object
 2   actor          1 non-null      object
 3   type           1 non-null      object
 4   role           1 non-null      object
 5   aw             1 non-null      object
 6   pic            0 non-null      float64
 7   notes          0 non-null      float64
 8   |              0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 200.0+ bytes
None
D:deAntoni
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   AbA         6 non-null      object
 1   D:deAntoni  6 non-null      object
 2   actor       6 non-null      object
 3   type        6 non-null      object
 4   role        6 non-null      object
 5   aw          6 non-null      object
 6   pic         0 non-null      float64
 7   notes       0 non-null      float64
 8   |           0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 560.0+ bytes
None
D:Band
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ABd     2 non-null      object
 1   D:Band  2 non-null      object
 2   actor   2 non-null      object
 3   type    2 non-null      object
 4   role    2 non-null      object
 5   aw      2 non-null      object
 6   pic     0 non-null      float64
 7   notes   0 non-null      float64
 8   |       0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 272.0+ bytes
None
D:Berliner
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ABe         1 non-null      object
 1   D:Berliner  1 non-null      object
 2   actor       1 non-null      object
 3   type        1 non-null      object
 4   role        1 non-null      object
 5   aw          1 non-null      object
 6   pic         0 non-null      float64
 7   notes       0 non-null      float64
 8   |           0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 200.0+ bytes
None
D:Ferrara
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   AbF        15 non-null     object
 1   D:Ferrara  15 non-null     object
 2   actor      15 non-null     object
 3   type       15 non-null     object
 4   role       15 non-null     object
 5   aw         15 non-null     object
 6   pic        0 non-null      float64
 7   notes      0 non-null      float64
 8   |          0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 1.2+ KB
None
D:Birkin
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ABi       9 non-null      object
 1   D:Birkin  9 non-null      object
 2   actor     9 non-null      object
 3   type      9 non-null      object
 4   role      9 non-null      object
 5   aw        9 non-null      object
 6   pic       0 non-null      float64
 7   notes     0 non-null      float64
 8   |         0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 776.0+ bytes
None
D:Blasetti
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ABl         3 non-null      object
 1   D:Blasetti  3 non-null      object
 2   actor       3 non-null      object
 3   type        3 non-null      object
 4   role        3 non-null      object
 5   aw          3 non-null      object
 6   pic         0 non-null      float64
 7   notes       0 non-null      float64
 8   |           0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 344.0+ bytes
None
D:Borman
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ABo       3 non-null      object
 1   D:Borman  3 non-null      object
 2   actor     3 non-null      object
 3   type      3 non-null      object
 4   role      3 non-null      object
 5   aw        3 non-null      object
 6   pic       0 non-null      float64
 7   notes     0 non-null      float64
 8   |         0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 344.0+ bytes
None
D:A.Brooks
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ABr         24 non-null     object
 1   D:A.Brooks  24 non-null     object
 2   actor       24 non-null     object
 3   type        24 non-null     object
 4   role        24 non-null     object
 5   aw          24 non-null     object
 6   pic         0 non-null      float64
 7   notes       0 non-null      float64
 8   |           0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 1.8+ KB
None
D:A.Burns
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ABu        5 non-null      object
 1   D:A.Burns  5 non-null      object
 2   actor      5 non-null      object
 3   type       5 non-null      object
 4   role       5 non-null      object
 5   aw         5 non-null      object
 6   pic        0 non-null      float64
 7   notes      0 non-null      float64
 8   |          0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 488.0+ bytes
None
D:A.Woods
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ABW        7 non-null      object
 1   D:A.Woods  7 non-null      object
 2   actor      7 non-null      object
 3   type       7 non-null      object
 4   role       7 non-null      object
 5   aw         6 non-null      object
 6   pic        1 non-null      object
 7   notes      0 non-null      float64
 8   |          0 non-null      float64
dtypes: float64(2), object(7)
memory usage: 632.0+ bytes
None
D:Buckhantz
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ABz          5 non-null      object
 1   D:Buckhantz  5 non-null      object
 2   actor        5 non-null      object
 3   type         5 non-null      object
 4   role         5 non-null      object
 5   aw           5 non-null      object
 6   pic          0 non-null      float64
 7   notes        0 non-null      float64
 8   |            0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 488.0+ bytes
None
D:Alb.Hughes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   AbH           3 non-null      object
 1   D:Alb.Hughes  3 non-null      object
 2   actor         3 non-null      object
 3   type          3 non-null      object
 4   role          3 non-null      object
 5   aw            3 non-null      object
 6   pic           0 non-null      float64
 7   notes         0 non-null      float64
 8   |             0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 344.0+ bytes
None
D:Crosland
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   AC          36 non-null     object
 1   D:Crosland  36 non-null     object
 2   actor       36 non-null     object
 3   type        36 non-null     object
 4   role        36 non-null     object
 5   aw          36 non-null     object
 6   pic         0 non-null      float64
 7   notes       0 non-null      float64
 8   |           0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 2.7+ KB
None
D:Cavalcanti
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ACa           38 non-null     object
 1   D:Cavalcanti  38 non-null     object
 2   actor         38 non-null     object
 3   type          38 non-null     object
 4   role          38 non-null     object
 5   aw            38 non-null     object
 6   pic           10 non-null     object
 7   notes         0 non-null      float64
 8   |             0 non-null      float64
dtypes: float64(2), object(7)
memory usage: 2.8+ KB
None
D:Cadiff
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ACf       4 non-null      object
 1   D:Cadiff  4 non-null      object
 2   actor     4 non-null      object
 3   type      4 non-null      object
 4   role      4 non-null      object
 5   aw        4 non-null      object
 6   pic       0 non-null      float64
 7   notes     0 non-null      float64
 8   |         0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 416.0+ bytes
None
D:Gonsalvi
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   AcG         1 non-null      object
 1   D:Gonsalvi  1 non-null      object
 2   actor       1 non-null      object
 3   type        1 non-null      object
 4   role        1 non-null      object
 5   aw          1 non-null      object
 6   pic         0 non-null      float64
 7   notes       0 non-null      float64
 8   |           0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 200.0+ bytes
None
D:Crosland~jr
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ACj            84 non-null     object
 1   D:Crosland~jr  84 non-null     object
 2   actor          84 non-null     object
 3   type           84 non-null     object
 4   role           84 non-null     object
 5   aw             84 non-null     object
 6   pic            0 non-null      float64
 7   notes          0 non-null      float64
 8   |              0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 6.0+ KB
None
D:A.Clark
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ACl        5 non-null      object
 1   D:A.Clark  5 non-null      object
 2   actor      5 non-null      object
 3   type       5 non-null      object
 4   role       5 non-null      object
 5   aw         5 non-null      object
 6   pic        0 non-null      float64
 7   notes      0 non-null      float64
 8   |          0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 488.0+ bytes
None
D:Crabtree
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ACt         1 non-null      object
 1   D:Crabtree  1 non-null      object
 2   actor       1 non-null      object
 3   type        1 non-null      object
 4   role        1 non-null      object
 5   aw          1 non-null      object
 6   pic         0 non-null      float64
 7   notes       0 non-null      float64
 8   |           0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 200.0+ bytes
None
D:Cuaron
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ACu       9 non-null      object
 1   D:Cuaron  9 non-null      object
 2   actor     9 non-null      object
 3   type      9 non-null      object
 4   role      9 non-null      object
 5   aw        9 non-null      object
 6   pic       0 non-null      float64
 7   notes     0 non-null      float64
 8   |         0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 776.0+ bytes
None
D:Cavalier
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ACv         3 non-null      object
 1   D:Cavalier  3 non-null      object
 2   actor       3 non-null      object
 3   type        3 non-null      object
 4   role        3 non-null      object
 5   aw          3 non-null      object
 6   pic         0 non-null      float64
 7   notes       0 non-null      float64
 8   |           0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 344.0+ bytes
None
D:Cox
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ACx     8 non-null      object
 1   D:Cox   8 non-null      object
 2   actor   8 non-null      object
 3   type    8 non-null      object
 4   role    8 non-null      object
 5   aw      8 non-null      object
 6   pic     0 non-null      float64
 7   notes   0 non-null      float64
 8   |       0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 704.0+ bytes
None
D:Cayatte
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ACy        12 non-null     object
 1   D:Cayatte  12 non-null     object
 2   actor      12 non-null     object
 3   type       12 non-null     object
 4   role       12 non-null     object
 5   aw         12 non-null     object
 6   pic        0 non-null      float64
 7   notes      0 non-null      float64
 8   |          0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 992.0+ bytes
None
D:Dovzhenko
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AD           3 non-null      object
 1   D:Dovzhenko  3 non-null      object
 2   actor        3 non-null      object
 3   type         3 non-null      object
 4   role         3 non-null      object
 5   aw           3 non-null      object
 6   pic          0 non-null      float64
 7   notes        0 non-null      float64
 8   |            0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 344.0+ bytes
None
D:DegliAbbati
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ADA            2 non-null      object
 1   D:DegliAbbati  2 non-null      object
 2   actor          2 non-null      object
 3   type           2 non-null      object
 4   role           2 non-null      object
 5   aw             2 non-null      object
 6   pic            0 non-null      float64
 7   notes          0 non-null      float64
 8   |              0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 272.0+ bytes
None
D:Brunel
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   AdB       4 non-null      object
 1   D:Brunel  4 non-null      object
 2   actor     4 non-null      object
 3   type      4 non-null      object
 4   role      4 non-null      object
 5   aw        4 non-null      object
 6   pic       0 non-null      float64
 7   notes     0 non-null      float64
 8   |         0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 416.0+ bytes
None
D:Dienstag
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ADg         2 non-null      object
 1   D:Dienstag  2 non-null      object
 2   actor       2 non-null      object
 3   type        2 non-null      object
 4   role        2 non-null      object
 5   aw          2 non-null      object
 6   pic         0 non-null      float64
 7   notes       0 non-null      float64
 8   |           0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 272.0+ bytes
None
D:Lyne
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AdL     38 non-null     object
 1   D:Lyne  38 non-null     object
 2   actot   38 non-null     object
 3   type    38 non-null     object
 4   role    38 non-null     object
 5   aw      38 non-null     object
 6   pic     1 non-null      object
 7   notes   0 non-null      float64
 8   |       0 non-null      float64
dtypes: float64(2), object(7)
memory usage: 2.8+ KB
None
D:Dreifuss
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ADr         7 non-null      object
 1   D:Dreifuss  7 non-null      object
 2   actor       7 non-null      object
 3   type        7 non-null      object
 4   role        7 non-null      object
 5   aw          7 non-null      object
 6   pic         0 non-null      float64
 7   notes       0 non-null      float64
 8   |           0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 632.0+ bytes
None
D:deToth
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ADT       15 non-null     object
 1   D:deToth  15 non-null     object
 2   actor     15 non-null     object
 3   type      15 non-null     object
 4   role      15 non-null     object
 5   aw        13 non-null     object
 6   pic       0 non-null      float64
 7   notes     1 non-null      object
 8   |         1 non-null      object
dtypes: float64(1), object(8)
memory usage: 1.2+ KB
None
D:A.Davis
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ADv        12 non-null     object
 1   D:A.Davis  12 non-null     object
 2   actor      12 non-null     object
 3   type       12 non-null     object
 4   role       12 non-null     object
 5   aw         12 non-null     object
 6   pic        1 non-null      object
 7   notes      0 non-null      float64
 8   |          0 non-null      float64
dtypes: float64(2), object(7)
memory usage: 992.0+ bytes
None
D:Dwan
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113 entries, 0 to 112
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ADw     113 non-null    object
 1   D:Dwan  113 non-null    object
 2   actor   113 non-null    object
 3   type    113 non-null    object
 4   role    113 non-null    object
 5   aw      113 non-null    object

In [151]:
castsTable

                movie             actor  type                           role
0         T:Pygmalion     Leslie Howard  \Sci     R:smug professor "Higgins"
1         T:Pygmalion      Wendy Hiller  \Inn          R:flower girl "Eliza"
2         T:Pygmalion    Wilfrid Lawson  \Und            R:friend "Dolittle"
3         T:Pygmalion  Scott Sunderland  \Und  R:betting Colonel "Pickering"
4         T:Pygmalion        Marie Lohr  \Und           R:wife "Mrs.Higgins"
...               ...               ...   ...                            ...
4067    T:Dr.Dolittle      Julie kavner  \Voi                            RU:
4068    T:Dr.Dolittle    John Leguizamo  \Voi                            RU:
4069    T:Dr.Dolittle   Ellen DeGeneres  \Voi                            RU:
4070    T:Dr.Dolittle      Paul Reubens  \Voi                            RU:
4071  T:None so Blind  Maurice Costello  \Und                            RU:

[4072 rows x 4 columns]

In [152]:
actorsTable.to_csv('actors.csv')
castsTable.to_csv('casts.csv')